name: CI
on: push

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup node
        uses: guardian/actions-setup-node

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Lint files
        run: npm run lint
